/* autogenerated by Processing revision 1313 on 2026-03-27 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.io.File;
import java.util.Arrays;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class sticker_spinner extends PApplet {




int blue = 0xFF2BD1FC;
int grey = 0xFF333333;

Grid grid;
Noise noise;
RasterBars rasterBars;
Bytebeat bytebeat;
Plasma plasma;
OpArt opArt;
ArcadeShag arcadeShag;
CommodoreTunnel commodoreTunnel;
VectorTunnel vectorTunnel;

MidiHandler midiHandler;

PImage[] stickerFiles;
Sticker[] stickers;

int pickBackground;
int pickSticker = 1;
int pickStickerRoutine = 1;

boolean releaseBackground = false;

public void setup() {
  /* size commented out by preprocessor */;
  //size(320, 240);
  noCursor();
  /* noSmooth commented out by preprocessor */;
  imageMode(CENTER);

  // Get list of files in data folder and filter for images
  File dataFolder = new File(dataPath(""));
  File[] files = dataFolder.listFiles();
  Arrays.sort(files); // Sort files alphabetically

  int numImages = 0;
  for (File file : files) {
    if (isImageFile(file)) {
      numImages++;
    }
  }

  stickerFiles = new PImage[numImages];
  stickers = new Sticker[numImages];

  int index = 0;
  for (File file : files) {
    if (isImageFile(file)) {
      stickerFiles[index] = loadImage(file.getName());
      stickers[index] = new Sticker(stickerFiles[index]);
      index++;
    }
  }

  grid = new Grid();
  noise = new Noise(24);
  rasterBars = new RasterBars();
  bytebeat = new Bytebeat(10, 5);
  plasma = new Plasma(10);  // Initialize the visualizer with pixelSize
  opArt = new OpArt(2, 100, 10); // rotationSpeed, tileSize, stepSize, frameDelay
  arcadeShag = new ArcadeShag(0.02f, 20, 4);
  commodoreTunnel = new CommodoreTunnel(16, 0.05f);
  commodoreTunnel.setup();
  vectorTunnel = new VectorTunnel(12, 30, 40, 0.25f, 80);

  midiHandler = new MidiHandler(this);
  midiHandler.setup();
}

public void draw() {

  if (!releaseBackground) {
    background(0);
  }

  // Draw background
  switch (pickBackground) {
  default:
    rasterBars.update(); // Bug if removed for some reason
    break;
  case 1:
    grid.update(blue);
    break;
  case 2:
    noise.update();
    break;
  case 3:
    rasterBars.update();
    break;
  case 4:
    bytebeat.updateFrame();
    bytebeat.drawFrame();
    break;
  case 5:
    plasma.updatePalette();  // Update the color palette
    plasma.drawPlasma();     // Draw the plasma effect
    break;
  case 6:
    opArt.display();
    break;
  case 7:
    arcadeShag.display();
    break;
  case 8:
    commodoreTunnel.display();
    break;
  case 9:
    vectorTunnel.display();
    break;
  case 10:

    break;
  }

  // Draw foreground
  translate(displayWidth / 2, displayHeight / 2);
  if (pickSticker > 0 && pickSticker <= stickers.length) {
    handleStickerRoutine(stickers[pickSticker - 1], pickStickerRoutine);
  }
}

public void handleStickerRoutine(Sticker sticker, int routine) {
  switch (routine) {
  case 1:
    // Subtle hover effect
    sticker.hover(0.12f, 2); // Slower rate, more noticeable hover
    break;
  case 2:
    // Dynamic bounce effect
    sticker.bounce(0.18f, 0.7f, 1.3f); // Slightly faster, more exaggerated bounce
    break;
  case 3:
    // Wobble effect with small amplitude
    sticker.wobble(0.08f, 0.15f); // Slower wobble, more subtle
    break;
  case 4:
    // Rotate and scale with dramatic range
    sticker.rotateAndScale(0.03f, 4); // Slower rate, wider scale range for more drama
    break;
  case 5:
    // Pulsate with stronger scaling
    sticker.pulsate(0.06f, 0.8f, 8); // More pronounced scale range, faster rate
    break;
  case 6:
    // Smooth fade in and out
    sticker.fadeInOut(0.02f); // Keep rate slow for a smooth fade
    break;
  case 7:
    // Spin horizontally (already defined)
    sticker.spinHorizontal();
    break;
  case 8:
    // Spin vertically (already defined)
    sticker.spinVertical();
    break;
  case 9:
    // Spin flat to the right (already defined)
    sticker.spinFlatRight();
    break;
  case 10:
    // Spin flat to the left (already defined)
    sticker.spinFlatLeft();
    break;
  }
}

public boolean isImageFile(File file) {
  String[] imageExtensions = { "gif", "png", "jpg", "jpeg" };
  String fileName = file.getName().toLowerCase();
  for (String ext : imageExtensions) {
    if (fileName.endsWith(ext)) {
      return true;
    }
  }
  return false;
}

public void dispose() {
  if (midiHandler != null) midiHandler.close();
}
class ArcadeShag {
  float noiseScale;
  float stepSize;
  int strokeWeight;

  ArcadeShag(float noiseScale, float stepSize, int strokeWeight) {
    this.noiseScale = noiseScale;
    this.stepSize = stepSize;
    this.strokeWeight = strokeWeight;
  }

  public void display() {
    background(0);
  
    float time = millis() * 0.001f;
  
    for (float i = 0; i < width; i += this.stepSize) {
      for (float j = 0; j < height; j += this.stepSize) {
        float xNoise = noise(i * this.noiseScale, j * this.noiseScale, time);
        float yNoise = noise(i * this.noiseScale, j * this.noiseScale + 1000, time);
        float angle = TWO_PI * xNoise;
      
        float x1 = i + this.stepSize * cos(angle);
        float y1 = j + this.stepSize * sin(angle);
      
        float r = map(cos(TWO_PI * xNoise + time), -1, 1, 0, 255);
        float g = map(cos(TWO_PI * yNoise + time), -1, 1, 0, 255);
        float b = map(cos(TWO_PI * (xNoise + yNoise) + time), -1, 1, 0, 255);
        pushMatrix();
        scale(2);
        stroke(r, g, b);
        strokeWeight(this.strokeWeight);
        line(i, j, x1, y1);
        popMatrix();
      }
    }
  }
}
class Bytebeat {
  int t;  // Time variable
  int pixelSize;  // Size of each "pixel" in pixels
  int frameDelay;  // Number of frames to hold each frame before updating
  int frameCounter;  // Counter to track the number of frames
  int[] pixelColors;  // Array to store pixel colors

  Bytebeat(int pixelSize, int frameDelay) {
    this.t = 0;
    this.pixelSize = pixelSize;
    this.frameDelay = frameDelay;
    this.frameCounter = 0;
    this.pixelColors = new int[(width / pixelSize) * (height / pixelSize)];
  }

  public void updateFrame() {
    frameCounter++;  // Increment the frame counter

    if (frameCounter >= frameDelay) {
      // Reset the frame counter
      frameCounter = 0;

      // Update the pixel colors
      int index = 0;
      for (int y = 0; y < height; y += pixelSize) {
        for (int x = 0; x < width; x += pixelSize) {
          // Use a bytebeat formula to generate a value
          //int value = (t * (x & ((y ^ 255) >> 1))) & 255; // Adjusted to avoid dimness

          // Uncomment one of the following formulas to try different effects
          // int value = (t + (x * y)) & 255;  // Default bytebeat formula
          // int value = (t * (x ^ y)) & 255;
          // int value = (t * ((x & y) | (x ^ y))) & 255;
          //// int value = (t * (x | y)) & 255;
          // int value = (t * (x & (y >> 4))) & 255;
          // int value = ((t >> 1) & (x ^ y)) & 255;
          // int value = (t * (x >> (y & 3))) & 255;
          // int value = (t ^ ((x & t) | (y >> 3))) & 255;
          // int value = ((t >> 2) | (x & y)) & 255; // Adjusted to avoid being too slow
          // int value = (t * ((x ^ y) >> 2)) & 255; // Adjusted to avoid a black screen
           int value = (t * (x | (y >> 2))) & 255;
          // int value = ((t & (x >> 3)) | (y >> 1)) & 255; // Adjusted for better visibility
           //int value = ((t & ((x * y) >> 1)) | 128) & 255; // Adjusted to avoid black screen

          // Generate a color based on the value
          int col;
          float brightness = map(value, 0, 255, 0, 1);
          switch (value % 3) {
            case 0: col = color(255 * brightness, 0, 0); break;  // Red gradient
            case 1: col = color(0, 255 * brightness, 0); break;  // Green gradient
            case 2: col = color(0, 0, 255 * brightness); break;  // Blue gradient
            default: col = color(255 * brightness, 255 * brightness, 255 * brightness); break;  // White gradient
          }

          // Store the color in the array
          pixelColors[index++] = col;
        }
      }

      t++;  // Increment time
    }
  }

  public void drawFrame() {
    // Draw the pixel colors stored in the array
    int index = 0;
    for (int y = 0; y < height; y += pixelSize) {
      for (int x = 0; x < width; x += pixelSize) {
        fill(pixelColors[index++]);
        noStroke();
        rect(x, y, pixelSize, pixelSize);
      }
    }
  }
}
class CommodoreTunnel {
  int pixelSize;
  int cols, rows;
  float[][] wave;
  float angle;
  float waveSpeed;
  int[] palette;
  int pixelHeight; // Declare pixelHeight as an int

  CommodoreTunnel(int pixelSize, float waveSpeed) {
    this.pixelSize = pixelSize;
    this.waveSpeed = waveSpeed;
    this.angle = 0.0f;
    this.palette = new int[]{
      0xFFFFFFFF, 0xFFC9D487, 0xFF9AE29B, 0xFFADADAD, 0xFFCB7E75,
      0xFF9F4E44, 0xFFA1683C, 0xFF626262, 0xFF898989, 0xFF887ECB,
      0xFF6ABFC6, 0xFFA057A3, 0xFF5CAB5E, 0xFF50459B, 0xFF6D5412,
      0xFF000000
    };
    this.pixelHeight = PApplet.parseInt(pixelSize * 0.75f); // Convert to int
  }

  public void setup() {
    noStroke();
    /* size commented out by preprocessor */;
    cols = width / pixelSize;
    rows = height / pixelHeight; // Adjust rows to use pixelHeight
    wave = new float[cols][rows];
    /* noSmooth commented out by preprocessor */; // Disable anti-aliasing for crisp pixel edges
  }

  public void updateWave() {
    for (int x = 0; x < cols; x++) {
      for (int y = 0; y < rows; y++) {
        float distance = dist(x * pixelSize, y * pixelHeight, width / 2, height / 2);
        wave[x][y] = sin(angle + distance * 0.1f);
      }
    }
  }

  public void drawWave() {
    for (int x = 0; x < cols; x++) {
      for (int y = 0; y < rows; y++) {
        float value = wave[x][y];
        int colorIndex = PApplet.parseInt(map(value, -1, 1, 0, palette.length - 1));
        fill(palette[colorIndex]);
        rect(x * pixelSize, y * pixelHeight, pixelSize, pixelHeight); // Use pixelHeight for height
      }
    }
  }

  public void shiftPalette() {
    int last = palette[palette.length - 1];
    for (int i = palette.length - 1; i > 0; i--) {
      palette[i] = palette[i - 1];
    }
    palette[0] = last;
  }

  public void display() {
    background(0);
    updateWave();
    noStroke();
    drawWave();
    if (frameCount % 64 == 0) {
      shiftPalette(); // Shift the palette colors
    }
    angle += waveSpeed;
  }
}
class Grid {
  float gridStroke;
  boolean gridGrow;
  float spin;
  float lineSize;

  Grid() {
    gridStroke = 0;
    gridGrow = true;
    lineSize = 4;
  }

  public void update(int colr) {
    pushMatrix();
    translate(displayWidth/2, displayHeight/2);
    
    if (spin >= TWO_PI){
      spin = 0;
    } else {
      spin += .02f;
    }
    rotate(cos(spin));
    stroke(colr);
    strokeWeight(lineSize);

    for (int i = -displayWidth; i < displayWidth; i += 128) {
      line(i, -displayWidth, i, displayWidth);
      for (int x = -displayWidth; x < displayWidth; x += 128) {
        line(-displayWidth, x, displayWidth, x);
      }
    }

    if (gridGrow == true) {
      lineSize += .25f;
    } else {
      lineSize -= .25f;
    }

    if (lineSize <= .3f) {
      gridGrow = true;
    }
    if (lineSize >= 32) {
      gridGrow = false;
    }
    popMatrix();
  }
}
public void handleMidiInput(int pitch, int velocity) {
  switch (pitch) {
    case 48: pickSticker = 0; break; // C2 delete sticker
    case 49: pickSticker = 1; break; // C#
    case 50: pickSticker = 2; break; // D
    case 51: pickSticker = 3; break; // D#
    case 52: pickSticker = 4; break; // E
    case 53: pickSticker = 5; break; // F
    case 54: pickSticker = 6; break; // F#
    case 55: pickSticker = 7; break; // G
    case 56: pickSticker = 8; break; // G#
    case 57: pickSticker = 9; break; // A

    case 60: pickBackground = 1; break; // C3
    case 61: pickBackground = 2; break; // C#
    case 62: pickBackground = 3; break; // D
    case 63: pickBackground = 4; break; // D#
    case 64: pickBackground = 5; break; // E
    case 65: pickBackground = 6; break; // F
    case 66: pickBackground = 7; break; // F#
    case 67: pickBackground = 8; break; // G

    case 72: pickStickerRoutine = 1; break; // C4
    case 73: pickStickerRoutine = 2; break; // C#
    case 74: pickStickerRoutine = 3; break; // D
    case 75: pickStickerRoutine = 4; break; // D#
    case 76: pickStickerRoutine = 5; break; // E
    case 77: pickStickerRoutine = 6; break; // F
    case 78: pickStickerRoutine = 7; break; // F#
    case 79: pickStickerRoutine = 8; break; // G

    case 80: releaseBackground = true; break; // G#4 (example for space bar equivalent)
    case 81: releaseBackground = false; break; // A4 (example for space bar release)
  }
}
public void keyPressed() {
//  if (key == '0') {
//    pickSticker = 0;
//  }
//  if (key == '1') {
//    pickSticker = 1;
//  }
//  if (key == '2') {
//    pickSticker = 2;
//  }
//  if (key == '3') {
//    pickSticker = 3;
//  }
//  if (key == '4') {
//    pickSticker = 4;
//  }
//  if (key == '5') {
//    pickSticker = 5;
//  }
//  if (key == '6') {
//    pickSticker = 6;
//  }
//  if (key == '7') {
//    pickSticker = 7;
//  }
//  if (key == '8') {
//    pickSticker = 8;
//  }
//  if (key == '9') {
//    pickSticker = 9;
//  }
//
//  if (key == 'a' || key == 'A') {
//    pickBackground = 1;
//  }
//  if (key == 's' || key == 'S') {
//    pickBackground = 2;
//  }
//  if (key == 'd' || key == 'D') {
//    pickBackground = 3;
//  }
//  if (key == 'f' || key == 'F') {
//    pickBackground = 4;
//  }
//  if (key == 'g' || key == 'G') {
//    pickBackground = 5;
//  }
//  if (key == 'h' || key == 'H') {
//    pickBackground = 6;
//  }
//  if (key == 'j' || key == 'J') {
//    pickBackground = 7;
//  }
//  if (key == 'k' || key == 'K') {
//    pickBackground = 8;
//  }
//  if (key == 'l' || key == 'L') {
//    pickBackground = 9;
//  }
//  if (key == ';' || key == ';') {
//    pickBackground = 10;
//  }
//
//  if (key == 'q' || key == 'Q') {
//    pickStickerRoutine = 1;
//  }
//  if (key == 'w' || key == 'W') {
//    pickStickerRoutine = 2;
//  }
//  if (key == 'e' || key == 'E') {
//    pickStickerRoutine = 3;
//  }
//  if (key == 'r' || key == 'R') {
//    pickStickerRoutine = 4;
//  }
//  if (key == 'y' || key == 'Y') {
//    pickStickerRoutine = 5;
//  }
//  if (key == 't' || key == 'T') {
//    pickStickerRoutine = 6;
//  }
//  if (key == 'u' || key == 'U') {
//    pickStickerRoutine = 7;
//  }
//  if (key == 'i' || key == 'I') {
//    pickStickerRoutine = 8;
//  }
//  if (key == 'o' || key == 'O') {
//    pickStickerRoutine = 9;
//  }
//  if (key == 'p' || key == 'P') {
//    pickStickerRoutine = 10;
//  }
//
//  if (key == ' ') {
//    releaseBackground = true;
//  }
//
//
//  if (key == CODED) {
//    if (keyCode == LEFT) {
//      pickSticker--;
//      if (pickSticker < 0) pickSticker = 9; // Loop around if below minimum
//    }
//    if (keyCode == UP) {
//      pickBackground--;
//      if (pickBackground < 1) pickBackground = 8; // Loop around if below minimum
//    }
//    if (keyCode == RIGHT) {
//      pickSticker++;
//      if (pickSticker > 9) pickSticker = 0; // Loop around if above maximum
//    }
//
//    if (keyCode == DOWN) {
//      pickBackground++;
//      if (pickBackground > 8) pickBackground = 1; // Loop around if above maximum
//    }
//  }
}

public void keyReleased() {
//  if (key == ' ') {
//    releaseBackground = false;
//  }
}
class Noise {
  float[] x;
  float[] strokeWeights;
  float[] strokeColors;
  int numLines;

  Noise(int numLines) {
    this.numLines = numLines;
    x = new float[numLines];
    strokeWeights = new float[numLines];
    strokeColors = new float[numLines];
    initializeLines();
  }

  public void initializeLines() {
    for (int i = 0; i < numLines; i++) {
      x[i] = random(displayWidth);
      strokeWeights[i] = random(1, 6);
      strokeColors[i] = random(255);
    }
  }

  public void updateLines() {
    for (int i = 0; i < numLines; i++) {
      x[i] = random(displayWidth);
      strokeWeights[i] = random(1, 6);
      strokeColors[i] = random(255);
    }
  }

  public void drawLines() {
    for (int i = 0; i < numLines; i++) {
      strokeWeight(strokeWeights[i]);
      stroke(strokeColors[i]);
      line(x[i], 0, x[i], height);
    }
  }

  public void update() {
    if (frameCount % 8 == 0) {
      updateLines();
    }
    drawLines();
  }
}
class OpArt {
  int tileSize;
  float rotationSpeed; // Speed of rotation for animation
  float stepSize; // Step size for pixelated effect
  float rotationAngle = 0; // Store the current rotation angle

  OpArt(float rotationSpeed, int tileSize, float stepSize) {
    this.rotationSpeed = rotationSpeed;
    this.tileSize = tileSize;
    this.stepSize = stepSize;
  }

  public void display() {
    // Update the rotation angle based on the rotation speed
    rotationAngle += radians(rotationSpeed);

    for (int y = 0; y < height; y += tileSize) {
      for (int x = 0; x < width; x += tileSize) {
        pushMatrix();
        scale(3.78f);
        translate(x + tileSize / 2, y + tileSize / 2);
        rotate(rotationAngle % TWO_PI); // Use the updated rotation angle
        drawTile(tileSize / 2);
        popMatrix();
      }
    }
  }

  public void drawTile(float halfSize) {
    stroke(255); // White lines
    strokeWeight(1);
    fill(0);
    for (float i = halfSize; i > 0; i -= stepSize) { // Adjust step for pixelated effect
      rectMode(CENTER);
      rect(0, 0, i * 2, i * 2);
    }
  }
}
class Plasma {
  int[] pal;
  int[] buffer;
  int pixelSize;
  int plasmaWidth, plasmaHeight;
  int[] baseColors;

  Plasma(int pixelSize) {
    this.pixelSize = pixelSize;
    this.baseColors = new int[] {color(255, 0, 255), color(0, 255, 255), color(255, 255, 255), color(0, 0, 0)}; // magenta, cyan, white, black
    this.pal = new int[128];
    this.plasmaWidth = width;
    this.plasmaHeight = height;
    this.buffer = new int[plasmaWidth * plasmaHeight];
    initializeBuffer();
  }

  public void initializeBuffer() {
    for (int x = 0; x < plasmaWidth; x++) {
      for (int y = 0; y < plasmaHeight; y++) {
        buffer[x + y * plasmaWidth] = PApplet.parseInt(((128 + (128 * sin(x / 16.0f))) // Increased frequency
          + (128 + (128 * cos(y / 16.0f))) // Increased frequency
          + (128 + (128 * sin(sqrt((x * x + y * y)) / 16.0f)))) / 4); // Increased frequency
      }
    }
  }

  public void updatePalette() {
    float s_1, s_2;
    for (int i = 0; i < 128; i++) {
      s_1 = sin(i * PI / 12.5f); // Increased frequency
      s_2 = sin(i * PI / 25 + PI / 4); // Increased frequency
      pal[i] = interpolateColors(s_1, s_2);
    }
  }

  public int interpolateColors(float s1, float s2) {
    int c1 = PApplet.parseInt(map(s1, -1, 1, 0, baseColors.length - 1));
    int c2 = (c1 + 1) % baseColors.length;
    float ratio = (s1 + 1) / 2; // map s1 from [-1, 1] to [0, 1]
    return lerpColor(baseColors[c1], baseColors[c2], ratio * (s2 + 1) / 2); // map s2 from [-1, 1] to [0, 1]
  }

  public void drawPlasma() {
    loadPixels();
    for (int x = 0; x < width; x += pixelSize) {
      for (int y = 0; y < height; y += pixelSize) {
        int px = x / pixelSize;
        int py = y / pixelSize;
        int col = pal[(buffer[px + py * plasmaWidth] + frameCount) & 127];
        for (int dx = 0; dx < pixelSize; dx++) {
          for (int dy = 0; dy < pixelSize; dy++) {
            int sx = x + dx;
            int sy = y + dy;
            if (sx < width && sy < height) {
              pixels[sx + sy * width] = col;
            }
          }
        }
      }
    }
    updatePixels();
  }
}
class RasterBars {
  float rectSize = 40;
  int[] colorArray = {
    0xFFFFC122,
    0xFFFFCF45,
    0xFFFA5DA3,
    0xFF00B01F,
    0xFFE80235,
    0xFF95A4D7,
    0xFF80C615,
    0xFF02ADE6,
    0xFF0190D8,
  };
  int[] directions; // Array to store direction for each rectangle
  float[] positions; // Array to store y-position for each rectangle
  float speed; // Speed for all rectangles
  float spacing; // Spacing between rectangles
  int frameDelay; // Frame delay between starting positions
  float waveFrequency = 0.05f; // Frequency of the sine wave
  float waveAmplitude = 50; // Amplitude of the sine wave

  RasterBars() {
    rectMode(CENTER);
    directions = new int[colorArray.length]; // Same number of directions as colors
    positions = new float[colorArray.length];
    speed = 10; // Set the speed for all rectangles
    spacing = rectSize + 10; // Set spacing to 10 pixels more than the rectangle size
    frameDelay = 8; // Delay between starting each rectangle

    // Initialize directions and positions
    for (int i = 0; i < colorArray.length; i++) {
      directions[i] = 1; // All start moving downwards
      positions[i] = 0; // Start all rectangles at the top of the screen
    }
  }

  public void update() {
    // Draw rectangles and update their positions
    pushMatrix();
    for (int i = 0; i < colorArray.length; i++) {
      fill(colorArray[i]);
      noStroke();

      // Calculate sine wave effect for y position
      float sineWave = sin((frameCount + i * frameDelay) * waveFrequency) * waveAmplitude;

      // Apply sine wave effect to the vertical position
      float y = positions[i] + sineWave;
      
      // Draw the rectangle
      rect(displayWidth / 2, y, displayWidth, rectSize);
      
      // Only update position after its delay
      if (frameCount > i * frameDelay) {
        // Update positions based on direction and speed
        positions[i] += speed * directions[i];

        // Check boundary points and switch direction if reached
        if (positions[i] <= 0 || positions[i] >= height) {
          directions[i] *= -1; // Reverse direction
        }
      }
    }
    popMatrix();
  }
}
class Sticker {
  PImage img;
  boolean expand = true;
  float imageWidth;
  float imageHeight;
  boolean reverseImage = false;
  boolean spinHorizontal = true;
  float speed = 4;
  float spin;
  float scaleFactor;

  Sticker(PImage inComingImage) {
    img = inComingImage;
    // Determine the scale factor based on the larger dimension
    if (img.width > img.height) {
      scaleFactor = (displayWidth * 0.75f) / img.width;
    } else {
      scaleFactor = (displayHeight * 0.75f) / img.height;
    }
  }

  public void hover(float rate, float widen) {
    spin += rate;
    pushMatrix();
    scale(scaleFactor);
    translate(0, (sin(spin) * widen));
    image(img, 0, 0);
    popMatrix();
  }

  public void spinFlatRight() {
    spin += .02f;
    pushMatrix();
    rotate(spin);
    scale(scaleFactor);
    image(img, 0, 0);
    popMatrix();
  }

  public void spinFlatLeft() {
    spin -= .02f;
    pushMatrix();
    rotate(spin);
    scale(scaleFactor);
    image(img, 0, 0);
    popMatrix();
  }

  public void spinVertical() {
    if (reverseImage == false) {
      if (expand == true) {
        if (imageHeight >= img.height) {
          expand = false;
        } else {
          imageHeight += speed;
        }
      }
      if (expand == false) {
        if (imageHeight <= 0) {
          expand = true;
          reverseImage = true;
        } else {
          imageHeight -= speed;
        }
      }
    } else {
      if (expand == true) {
        if (imageHeight >= img.height) {
          expand = false;
        } else {
          imageHeight += speed;
        }
      }
      if (expand == false) {
        if (imageHeight <= 0) {
          expand = true;
          reverseImage = false;
        } else {
          imageHeight -= speed;
        }
      }
    }
    pushMatrix();
    if (reverseImage) {
      scale(-scaleFactor, scaleFactor);
    } else {
      scale(scaleFactor);
    } // Reverse the image if necessary
    image(img, 0, 0, img.width, imageHeight);
    popMatrix();
  }

  public void spinHorizontal() {
    if (reverseImage == false) {
      if (expand == true) {
        if (imageWidth >= img.width) {
          expand = false;
        } else {
          imageWidth += speed;
        }
      }
      if (expand == false) {
        if (imageWidth <= 0) {
          expand = true;
          reverseImage = true;
        } else {
          imageWidth -= speed;
        }
      }
    } else {
      if (expand == true) {
        if (imageWidth >= img.width) {
          expand = false;
        } else {
          imageWidth += speed;
        }
      }
      if (expand == false) {
        if (imageWidth <= 0) {
          expand = true;
          reverseImage = false;
        } else {
          imageWidth -= speed;
        }
      }
    }
    pushMatrix();
    if (reverseImage) {
      scale(-scaleFactor, scaleFactor);
    } else {
      scale(scaleFactor);
    } // Reverse the image if necessary
    image(img, 0, 0, imageWidth, img.height);
    popMatrix();
  }

  public void bounce(float rate, float minScale, float maxScale) {
    spin += rate;
    float scaleValue = map(sin(spin), -1, 1, minScale, maxScale);
    pushMatrix();
    scale(scaleFactor * scaleValue);
    image(img, 0, 0);
    popMatrix();
  }

  public void pulsate(float rate, float minScale, float maxScale) {
    spin += rate;
    // Stronger scaling effect for a more dynamic pulsation
    float scaleValue = map(sin(spin), -1, 1, minScale, maxScale);
    float alphaValue = map(sin(spin), -1, 1, 200, 255); // Maintain a subtle opacity change
    pushMatrix();
    tint(255, alphaValue); // Apply slight opacity change
    scale(scaleFactor * scaleValue); // Apply scaling
    image(img, 0, 0);
    noTint(); // Reset tint to default
    popMatrix();
  }


public void rotateAndScale(float rate, float scaleRange) {
  spin += rate;
  // Increase the scale range for more dramatic scaling
  float currentScale = map(sin(spin), -1, 1, scaleFactor - scaleRange * 4, scaleFactor + scaleRange * 4);
  pushMatrix();
  // Apply a more pronounced rotation
  rotate(spin * 1.2f);
  scale(currentScale);
  image(img, 0, 0);
  popMatrix();
}


  public void wobble(float rate, float angleRange) {
    spin += rate;
    float angle = sin(spin) * angleRange;
    pushMatrix();
    rotate(angle);
    scale(scaleFactor);
    image(img, 0, 0);
    popMatrix();
  }

  public void fadeInOut(float rate) {
    spin += rate;
    // Smooth fade in and out between full opacity and complete transparency
    float alphaValue = map(sin(spin), -1, 1, 0, 255);
    pushMatrix();
    tint(255, alphaValue); // Adjust opacity only
    scale(scaleFactor);
    image(img, 0, 0);
    noTint(); // Reset tint to default
    popMatrix();
  }
}
class VectorTunnel {
  int numLines;
  int numRings;
  float depth;
  float speed;
  float ringSpacing;

  VectorTunnel(int numLines, int numRings, float depth, float speed, float ringSpacing) {
    this.numLines = numLines;
    this.numRings = numRings;
    this.depth = depth;
    this.speed = speed;
    this.ringSpacing = ringSpacing;
  }

  public void display() {
    pushMatrix();
    translate(width / 2, height / 2); // Center of the screen

    float time = millis() * speed; // Time-based movement
    float loopLength = numRings * ringSpacing;

    for (int i = 0; i < numRings; i++) {
      float distance = (i * ringSpacing - time) % loopLength;

      if (distance < 0) {
        distance += loopLength;
      }

      float radius = depth + distance; // Radius of each ring

      beginShape();
      stroke(0, 255, 0); // Green color for vector effect
      strokeWeight(8);   // Thicker lines for retro look
      noFill();
      for (int j = 0; j < numLines; j++) {
        float angle = TWO_PI / numLines * j;
        float x = cos(angle) * radius;
        float y = sin(angle) * radius;

        // Push vertices towards the center as they get closer to the screen
        if (distance < ringSpacing / 2) {
          x *= distance / (ringSpacing / 2);
          y *= distance / (ringSpacing / 2);
        }

        vertex(x, y);
      }
      endShape(CLOSE);
    }
    popMatrix();
  }
}


  public void settings() { fullScreen();
noSmooth(); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "sticker_spinner" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
